micronaut:
  application:
    name: doublejoinbug
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 'doublejoinbug'
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: doublejoinbug
#    driverClassName: org.postgresql.Driver
#    schema: my_schema
##    maximum-pool-size: 10
##    minimum-idle: 2
#    schema-generate: CREATE_DROP

netty:
  default:
    allocator:
      max-order: 3
